export { default as Table } from './Table.svelte'
export { default as TableBody } from './TableBody.svelte'
export { default as TableCell } from './TableCell.svelte'
export { default as TableFoot } from './TableFoot.svelte'
export { default as TableHead } from './TableHead.svelte'
export { default as TableRow } from './TableRow.svelte'
